### ISSUE TITLE
HttpEndpoint - Invalid Regular Expression error

### ISSUE THREAD

**Issue by UncleHoppy** [DieProduktMacher/serverless-local-dev-server#6]
Windows 10, Node 6.11

Error:  Invalid regular expression: /^\http\echo\(?:([^\/]+?))\/?$/: Unmatched ')'
HttpEndpoint.js (15, ..)  

I assume this has something to do with the way Windows treats slashes.  If I update this line:

_this.path = path.join('/http', this.resourcePath)_

to be fixed:

this.path = path.posix.join('/http', this.resourcePath)

The error is gone and all works.

**Comment by tlimp** [comment]
Sorry for not being responsive on this one.
It is now implemented in version v0.3.1
