### ISSUE TITLE
Add additional path property to lambda event object

### ISSUE THREAD

**Issue by tmaslen** [DieProduktMacher/serverless-local-dev-server#9]
Hello,

This module almost does exactly what I need. However when running on AWS the event object that gets passed to the lambda has a property called `path` which is missing in this module.

Here's an example event object sent from API Gateway to my Lambda...

```
{ "resource": "/profile",
  "path": "/profile",
  "httpMethod": "GET",
  "headers": 
```

Here is the event object sent in the module...

```
{ httpMethod: 'GET',
  body: '{}',
  queryStringParameters: {},
  pathParameters: {}
}
```

I've made this available by editing `Server.js` on line 82...

```
lambdaEvent.path = endpoint.resourcePath;
```

Do you think this is a plausible change to the module? I'm happy to make a pull request.

Thanks for making this module, its super useful!

Regards,
/t

**Comment by tlimp** [comment]
Hello.
Even though we never had the need (obviously), it seems like a useful addition none the less.
So, it would be cool, if you could add it. We will be happy to merge your pull request.
Kind regards, Thomas

**Comment by tmaslen** [comment]
That's awesome, thank you.

Looking at the tests I'm unsure how to add a unit test for this?

Thanks,
/t
